spring:
  profiles:
    default: local
    group:
      "local": local, secret
      "prod": prod, secret

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: false
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enable: true

  kafka:
    consumer:
      enable-auto-commit: false
      properties:
        isolation:
          level: read_committed

logging:
  config: classpath:logback-spring.xml

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.example.consumer: debug

    org:
      hibernate:
        SQL: info
        #        SQL: debug
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  main:
    allow-bean-definition-overriding: true